<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MstProfessorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('mst_professors')->truncate();

        DB::table('mst_professors')->insert([
            0 => [
                'id' => 1,
                'name' => '相澤 勝治',
                'name_kana' => 'アイザワ　カツジ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            1 => [
                'id' => 2,
                'name' => '青木 章通',
                'name_kana' => 'アオキ　アキミチ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            2 => [
                'id' => 3,
                'name' => '渥美 幸雄',
                'name_kana' => 'アツミ　ユキオ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            3 => [
                'id' => 4,
                'name' => '石崎 徹',
                'name_kana' => 'イシザキ　トオル',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            4 => [
                'id' => 5,
                'name' => '一ノ宮 士郎',
                'name_kana' => 'イチノミヤ　シロウ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            5 => [
                'id' => 6,
                'name' => '今井 雅和',
                'name_kana' => 'イマイ　マサカズ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            6 => [
                'id' => 7,
                'name' => '岩田 弘尚',
                'name_kana' => 'イワタ　ヒロナオ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            7 => [
                'id' => 8,
                'name' => '植竹 朋文',
                'name_kana' => 'ウエタケ　トモフミ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            8 => [
                'id' => 9,
                'name' => '内田 欽三',
                'name_kana' => 'ウチダ　キンゾウ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            9 => [
                'id' => 10,
                'name' => '大曽根 匡',
                'name_kana' => 'オオソネ　タダシ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            10 => [
                'id' => 11,
                'name' => '大柳 康司',
                'name_kana' => 'オオヤナギ　コウジ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            11 => [
                'id' => 12,
                'name' => '荻原 幸子',
                'name_kana' => 'オギワラ　サチコ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            12 => [
                'id' => 13,
                'name' => '小沢 一郎',
                'name_kana' => 'オザワ　イチロウ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            13 => [
                'id' => 14,
                'name' => '金 成洙',
                'name_kana' => 'キム　ソンス',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            14 => [
                'id' => 15,
                'name' => '佐々木 浩二',
                'name_kana' => 'ササキ　コウジ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            15 => [
                'id' => 16,
                'name' => '佐藤 康一郎',
                'name_kana' => 'サトウ　コウイチロウ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            16 => [
                'id' => 17,
                'name' => '佐藤 暢',
                'name_kana' => 'サトウ　ヒロシ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            17 => [
                'id' => 18,
                'name' => '佐藤 満',
                'name_kana' => 'サトウ　ミツル',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            18 => [
                'id' => 19,
                'name' => '関根 純',
                'name_kana' => 'セキネ　ジュン',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            19 => [
                'id' => 20,
                'name' => '蔡　芢錫',
                'name_kana' => 'チエ　インソク',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            20 => [
                'id' => 21,
                'name' => '中村 太一',
                'name_kana' => 'ナカムラ　タイチ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            21 => [
                'id' => 22,
                'name' => '西山 貴弘',
                'name_kana' => 'ニシヤマ　タカヒロ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            22 => [
                'id' => 23,
                'name' => '根本 宮美子',
                'name_kana' => 'ネモト クミコ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            23 => [
                'id' => 24,
                'name' => '橋田 洋一郎',
                'name_kana' => 'ハシダ　ヨウイチロウ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            24 => [
                'id' => 25,
                'name' => '馬塲 杉夫',
                'name_kana' => 'ババ　スギオ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            25 => [
                'id' => 26,
                'name' => '廣石 忠司',
                'name_kana' => 'ヒロイシ　タダシ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            26 => [
                'id' => 27,
                'name' => '間嶋 崇',
                'name_kana' => 'マジマ　タカシ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            27 => [
                'id' => 28,
                'name' => '増子 惠一',
                'name_kana' => 'マスコ　ケイイチ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            28 => [
                'id' => 29,
                'name' => '松本 幸三',
                'name_kana' => 'マツモト　コウゾウ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            29 => [
                'id' => 30,
                'name' => '目黒 良門',
                'name_kana' => 'メグロ　ラモン',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            30 => [
                'id' => 31,
                'name' => '森本 祥一',
                'name_kana' => 'モリモト　ショウイチ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            31 => [
                'id' => 32,
                'name' => '矢澤 清明',
                'name_kana' => 'ヤザワ　キヨアキ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            32 => [
                'id' => 33,
                'name' => '山内 昌斗',
                'name_kana' => 'ヤマウチ　マサト',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            33 => [
                'id' => 34,
                'name' => '山崎 秀彦',
                'name_kana' => 'ヤマザキ　ヒデヒコ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            34 => [
                'id' => 35,
                'name' => '李 建平',
                'name_kana' => 'リ　ケンペイ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            35 => [
                'id' => 36,
                'name' => '渡辺 展男',
                'name_kana' => 'ワタナベ　ノリオ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            36 => [
                'id' => 37,
                'name' => '宇佐美 嘉弘',
                'name_kana' => 'ウサミ　ヨシヒロ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            37 => [
                'id' => 38,
                'name' => '奥村 経世',
                'name_kana' => 'オクムラ　ツネヨ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            38 => [
                'id' => 39,
                'name' => '倉持 俊弥',
                'name_kana' => 'クラモチ　トシヤ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            39 => [
                'id' => 40,
                'name' => '是永 隆文',
                'name_kana' => 'コレナガ　タカフミ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            40 => [
                'id' => 41,
                'name' => '坂口 幸雄',
                'name_kana' => 'サカグチ　ユキオ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            41 => [
                'id' => 42,
                'name' => '中村 世名',
                'name_kana' => 'ナカムラ　セナ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            42 => [
                'id' => 43,
                'name' => '巴山 竜来',
                'name_kana' => 'ハヤマ　タツキ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            43 => [
                'id' => 44,
                'name' => '福原 康司',
                'name_kana' => 'フクハラ　ヤスシ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            44 => [
                'id' => 45,
                'name' => '福山 文子',
                'name_kana' => 'フクヤマ　アヤコ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            45 => [
                'id' => 46,
                'name' => '宮川 宏',
                'name_kana' => 'ミヤガワ ヒロシ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            46 => [
                'id' => 47,
                'name' => '三宅 秀道',
                'name_kana' => 'ミヤケ　ヒデミチ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            47 => [
                'id' => 48,
                'name' => '山田 耕嗣',
                'name_kana' => 'ヤマダ　コウジ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            48 => [
                'id' => 49,
                'name' => '小川 博雅',
                'name_kana' => 'オガワ　ヒロマサ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            49 => [
                'id' => 50,
                'name' => '見山 謙一郎',
                'name_kana' => 'ミヤマ　ケンイチロウ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
        ]);
    }
}
