<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MstSubjectsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('mst_subjects')->truncate();

        DB::table('mst_subjects')->insert([
            0 => [
                'id' => 1,
                'name' => '専修大学入門ゼミナール',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            1 => [
                'id' => 2,
                'name' => 'キャリア入門',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            2 => [
                'id' => 3,
                'name' => 'あなたと自然科学',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            3 => [
                'id' => 4,
                'name' => 'スポーツリテラシー',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            4 => [
                'id' => 5,
                'name' => 'スポーツウェルネス',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            5 => [
                'id' => 6,
                'name' => '日本の文化',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            6 => [
                'id' => 7,
                'name' => '日本の文学',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            7 => [
                'id' => 8,
                'name' => '世界の文学',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            8 => [
                'id' => 9,
                'name' => '文学と現代世界',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            9 => [
                'id' => 10,
                'name' => '英語圏文学への招待',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            10 => [
                'id' => 11,
                'name' => '歴史の視点',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            11 => [
                'id' => 12,
                'name' => '歴史と地域・民衆',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            12 => [
                'id' => 13,
                'name' => '歴史と社会・文化',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            13 => [
                'id' => 14,
                'name' => '基礎心理学入門',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            14 => [
                'id' => 15,
                'name' => '応用心理学入門',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            15 => [
                'id' => 16,
                'name' => '哲学',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            16 => [
                'id' => 17,
                'name' => '倫理学',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            17 => [
                'id' => 18,
                'name' => '論理学入門',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            18 => [
                'id' => 19,
                'name' => 'ことばと論理',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            19 => [
                'id' => 20,
                'name' => '芸術学入門',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            20 => [
                'id' => 21,
                'name' => '異文化理解の人類学',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            21 => [
                'id' => 22,
                'name' => 'ジャーナリズムと現代',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            22 => [
                'id' => 23,
                'name' => '日本国憲法',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            23 => [
                'id' => 24,
                'name' => '法と社会',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            24 => [
                'id' => 25,
                'name' => '政治学入門',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            25 => [
                'id' => 26,
                'name' => '政治の世界',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            26 => [
                'id' => 27,
                'name' => '地理学への招待',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            27 => [
                'id' => 28,
                'name' => '社会学入門',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            28 => [
                'id' => 29,
                'name' => '現代の社会学',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            29 => [
                'id' => 30,
                'name' => '社会科学論',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            30 => [
                'id' => 31,
                'name' => '自然科学実験演習1',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            31 => [
                'id' => 32,
                'name' => '自然科学実験演習2',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            32 => [
                'id' => 33,
                'name' => '生物科学1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            33 => [
                'id' => 34,
                'name' => '生物科学1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            34 => [
                'id' => 35,
                'name' => '生物科学2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            35 => [
                'id' => 36,
                'name' => '生物科学2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            36 => [
                'id' => 37,
                'name' => '生物科学3a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            37 => [
                'id' => 38,
                'name' => '生物科学3b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            38 => [
                'id' => 39,
                'name' => '宇宙地球科学1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            39 => [
                'id' => 40,
                'name' => '宇宙地球科学1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            40 => [
                'id' => 41,
                'name' => '宇宙地球科学2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            41 => [
                'id' => 42,
                'name' => '宇宙地球科学2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            42 => [
                'id' => 43,
                'name' => '化学1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            43 => [
                'id' => 44,
                'name' => '化学1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            44 => [
                'id' => 45,
                'name' => '化学2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            45 => [
                'id' => 46,
                'name' => '化学2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            46 => [
                'id' => 47,
                'name' => '物理学1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            47 => [
                'id' => 48,
                'name' => '物理学1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            48 => [
                'id' => 49,
                'name' => '物理学2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            49 => [
                'id' => 50,
                'name' => '物理学2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            50 => [
                'id' => 51,
                'name' => '数理科学1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            51 => [
                'id' => 52,
                'name' => '数理科学1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            52 => [
                'id' => 53,
                'name' => '数理科学2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            53 => [
                'id' => 54,
                'name' => '数理科学2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            54 => [
                'id' => 55,
                'name' => '数理科学3a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            55 => [
                'id' => 56,
                'name' => '数理科学3b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            56 => [
                'id' => 57,
                'name' => '科学論1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            57 => [
                'id' => 58,
                'name' => '科学論1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            58 => [
                'id' => 59,
                'name' => '科学論2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            59 => [
                'id' => 60,
                'name' => '科学論2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            60 => [
                'id' => 61,
                'name' => '学際科目1',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            61 => [
                'id' => 62,
                'name' => '学際科目2',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            62 => [
                'id' => 63,
                'name' => '学際科目3',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            63 => [
                'id' => 64,
                'name' => '学際科目4',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            64 => [
                'id' => 65,
                'name' => '学際科目5',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            65 => [
                'id' => 66,
                'name' => '学際科目6',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            66 => [
                'id' => 67,
                'name' => '学際科目7',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            67 => [
                'id' => 68,
                'name' => '学際科目8',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            68 => [
                'id' => 69,
                'name' => '学際科目9',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            69 => [
                'id' => 70,
                'name' => '学際科目10',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            70 => [
                'id' => 71,
                'name' => '学際科目11',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            71 => [
                'id' => 72,
                'name' => '学際科目12',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            72 => [
                'id' => 73,
                'name' => 'テーマ科目',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            73 => [
                'id' => 74,
                'name' => '新領域科目1',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            74 => [
                'id' => 75,
                'name' => '新領域科目2',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            75 => [
                'id' => 76,
                'name' => '新領域科目3',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            76 => [
                'id' => 77,
                'name' => '新領域科目4',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            77 => [
                'id' => 78,
                'name' => '新領域科目5',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            78 => [
                'id' => 79,
                'name' => 'キャリア科目1',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            79 => [
                'id' => 80,
                'name' => 'キャリア科目2',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            80 => [
                'id' => 81,
                'name' => '教養テーマゼミナール1 ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            81 => [
                'id' => 82,
                'name' => '教養テーマゼミナール2 ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            82 => [
                'id' => 83,
                'name' => '教養テーマゼミナール3',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            83 => [
                'id' => 84,
                'name' => '教養テーマゼミナール論文',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            84 => [
                'id' => 85,
                'name' => 'アドバンストスポーツ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            85 => [
                'id' => 86,
                'name' => 'スポーツ論（健康と生涯スポーツ）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            86 => [
                'id' => 87,
                'name' => 'スポーツ論（オリンピックとスポーツ）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            87 => [
                'id' => 88,
                'name' => 'スポーツ論（スポーツコーチング）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            88 => [
                'id' => 89,
                'name' => 'スポーツ論（スポーツライフデザイン論）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            89 => [
                'id' => 90,
                'name' => 'スポーツ論（人類とスポーツ）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            90 => [
                'id' => 91,
                'name' => 'スポーツ論（トレーニング科学）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            91 => [
                'id' => 92,
                'name' => 'Basics of English （RL） 1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            92 => [
                'id' => 93,
                'name' => 'Basics of English （RL） 1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            93 => [
                'id' => 94,
                'name' => 'Intermediate English （RL） 1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            94 => [
                'id' => 95,
                'name' => 'Intermediate English （RL） 1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            95 => [
                'id' => 96,
                'name' => 'Basics of English （SW） 1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            96 => [
                'id' => 97,
                'name' => 'Basics of English （SW） 1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            97 => [
                'id' => 98,
                'name' => 'Intermediate English （SW） 1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            98 => [
                'id' => 99,
                'name' => 'Intermediate English （SW） 1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            99 => [
                'id' => 100,
                'name' => 'Basics of English （RL） 2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            100 => [
                'id' => 101,
                'name' => 'Basics of English （RL） 2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            101 => [
                'id' => 102,
                'name' => 'Intermediate English （RL） 2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            102 => [
                'id' => 103,
                'name' => 'Intermediate English （RL） 2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            103 => [
                'id' => 104,
                'name' => 'Basics of English （SW） 2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            104 => [
                'id' => 105,
                'name' => 'Basics of English （SW） 2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            105 => [
                'id' => 106,
                'name' => 'Intermediate English （SW） 2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            106 => [
                'id' => 107,
                'name' => 'Intermediate English （SW） 2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            107 => [
                'id' => 108,
                'name' => 'General English',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            108 => [
                'id' => 109,
                'name' => 'English Speaking a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            109 => [
                'id' => 110,
                'name' => 'English Speaking b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            110 => [
                'id' => 111,
                'name' => 'Computer Aided Instruction a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            111 => [
                'id' => 112,
                'name' => 'Computer Aided Instruction b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            112 => [
                'id' => 113,
                'name' => 'Computer Aided Instruction for TOEIC a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            113 => [
                'id' => 114,
                'name' => 'Computer Aided Instruction for TOEIC b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            114 => [
                'id' => 115,
                'name' => 'Advanced English a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            115 => [
                'id' => 116,
                'name' => 'Advanced English b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            116 => [
                'id' => 117,
                'name' => 'English Language and Cultures a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            117 => [
                'id' => 118,
                'name' => 'English Language and Cultures b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            118 => [
                'id' => 119,
                'name' => 'English Presentation a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            119 => [
                'id' => 120,
                'name' => 'English Presentation b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            120 => [
                'id' => 121,
                'name' => 'English Writing a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            121 => [
                'id' => 122,
                'name' => 'English Writing b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            122 => [
                'id' => 123,
                'name' => 'Screen English a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            123 => [
                'id' => 124,
                'name' => 'Screen English b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            124 => [
                'id' => 125,
                'name' => 'ドイツ語初級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            125 => [
                'id' => 126,
                'name' => 'ドイツ語初級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            126 => [
                'id' => 127,
                'name' => 'ドイツ語初級2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            127 => [
                'id' => 128,
                'name' => 'ドイツ語初級2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            128 => [
                'id' => 129,
                'name' => 'フランス語初級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            129 => [
                'id' => 130,
                'name' => 'フランス語初級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            130 => [
                'id' => 131,
                'name' => 'フランス語初級2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            131 => [
                'id' => 132,
                'name' => 'フランス語初級2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            132 => [
                'id' => 133,
                'name' => '中国語初級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            133 => [
                'id' => 134,
                'name' => '中国語初級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            134 => [
                'id' => 135,
                'name' => '中国語初級2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            135 => [
                'id' => 136,
                'name' => '中国語初級2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            136 => [
                'id' => 137,
                'name' => 'スペイン語初級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            137 => [
                'id' => 138,
                'name' => 'スペイン語初級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            138 => [
                'id' => 139,
                'name' => 'スペイン語初級2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            139 => [
                'id' => 140,
                'name' => 'スペイン語初級2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            140 => [
                'id' => 141,
                'name' => 'ロシア語初級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            141 => [
                'id' => 142,
                'name' => 'ロシア語初級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            142 => [
                'id' => 143,
                'name' => 'ロシア語初級2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            143 => [
                'id' => 144,
                'name' => 'ロシア語初級2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            144 => [
                'id' => 145,
                'name' => 'インドネシア語初級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            145 => [
                'id' => 146,
                'name' => 'インドネシア語初級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            146 => [
                'id' => 147,
                'name' => 'インドネシア語初級2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            147 => [
                'id' => 148,
                'name' => 'インドネシア語初級2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            148 => [
                'id' => 149,
                'name' => 'コリア語初級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            149 => [
                'id' => 150,
                'name' => 'コリア語初級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            150 => [
                'id' => 151,
                'name' => 'コリア語初級2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            151 => [
                'id' => 152,
                'name' => 'コリア語初級2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            152 => [
                'id' => 153,
                'name' => 'ドイツ語中級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            153 => [
                'id' => 154,
                'name' => 'ドイツ語中級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            154 => [
                'id' => 155,
                'name' => 'ドイツ語中級2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            155 => [
                'id' => 156,
                'name' => 'ドイツ語中級2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            156 => [
                'id' => 157,
                'name' => 'フランス語中級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            157 => [
                'id' => 158,
                'name' => 'フランス語中級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            158 => [
                'id' => 159,
                'name' => 'フランス語中級2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            159 => [
                'id' => 160,
                'name' => 'フランス語中級2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            160 => [
                'id' => 161,
                'name' => '中国語中級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            161 => [
                'id' => 162,
                'name' => '中国語中級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            162 => [
                'id' => 163,
                'name' => '中国語中級2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            163 => [
                'id' => 164,
                'name' => '中国語中級2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            164 => [
                'id' => 165,
                'name' => 'スペイン語中級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            165 => [
                'id' => 166,
                'name' => 'スペイン語中級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            166 => [
                'id' => 167,
                'name' => 'スペイン語中級2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            167 => [
                'id' => 168,
                'name' => 'スペイン語中級2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            168 => [
                'id' => 169,
                'name' => 'ロシア語中級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            169 => [
                'id' => 170,
                'name' => 'ロシア語中級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            170 => [
                'id' => 171,
                'name' => 'ロシア語中級2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            171 => [
                'id' => 172,
                'name' => 'ロシア語中級2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            172 => [
                'id' => 173,
                'name' => 'インドネシア語中級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            173 => [
                'id' => 174,
                'name' => 'インドネシア語中級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            174 => [
                'id' => 175,
                'name' => 'インドネシア語中級2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            175 => [
                'id' => 176,
                'name' => 'インドネシア語中級2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            176 => [
                'id' => 177,
                'name' => 'コリア語中級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            177 => [
                'id' => 178,
                'name' => 'コリア語中級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            178 => [
                'id' => 179,
                'name' => 'コリア語中級2a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            179 => [
                'id' => 180,
                'name' => 'コリア語中級2b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            180 => [
                'id' => 181,
                'name' => 'ドイツ語上級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            181 => [
                'id' => 182,
                'name' => 'ドイツ語上級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            182 => [
                'id' => 183,
                'name' => 'フランス語上級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            183 => [
                'id' => 184,
                'name' => 'フランス語上級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            184 => [
                'id' => 185,
                'name' => '中国語上級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            185 => [
                'id' => 186,
                'name' => '中国語上級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            186 => [
                'id' => 187,
                'name' => 'スペイン語上級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            187 => [
                'id' => 188,
                'name' => 'スペイン語上級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            188 => [
                'id' => 189,
                'name' => 'ロシア語上級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            189 => [
                'id' => 190,
                'name' => 'ロシア語上級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            190 => [
                'id' => 191,
                'name' => 'インドネシア語上級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            191 => [
                'id' => 192,
                'name' => 'インドネシア語上級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            192 => [
                'id' => 193,
                'name' => 'コリア語上級1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            193 => [
                'id' => 194,
                'name' => 'コリア語上級1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            194 => [
                'id' => 195,
                'name' => '選択ドイツ語1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            195 => [
                'id' => 196,
                'name' => '選択ドイツ語1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            196 => [
                'id' => 197,
                'name' => '選択フランス語1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            197 => [
                'id' => 198,
                'name' => '選択フランス語1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            198 => [
                'id' => 199,
                'name' => '選択中国語1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            199 => [
                'id' => 200,
                'name' => '選択中国語1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            200 => [
                'id' => 201,
                'name' => '選択スペイン語1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            201 => [
                'id' => 202,
                'name' => '選択スペイン語1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            202 => [
                'id' => 203,
                'name' => '選択コリア語1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            203 => [
                'id' => 204,
                'name' => '選択コリア語1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            204 => [
                'id' => 205,
                'name' => '選択アラビア語1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            205 => [
                'id' => 206,
                'name' => '選択アラビア語1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            206 => [
                'id' => 207,
                'name' => '選択イタリア語1a',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            207 => [
                'id' => 208,
                'name' => '選択イタリア語1b',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            208 => [
                'id' => 209,
                'name' => '世界の言語と文化（ドイツ語）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            209 => [
                'id' => 210,
                'name' => '世界の言語と文化（フランス語）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            210 => [
                'id' => 211,
                'name' => '世界の言語と文化（中国語）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            211 => [
                'id' => 212,
                'name' => '世界の言語と文化（スペイン語）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            212 => [
                'id' => 213,
                'name' => '世界の言語と文化（ロシア語）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            213 => [
                'id' => 214,
                'name' => '世界の言語と文化（インドネシア語）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            214 => [
                'id' => 215,
                'name' => '世界の言語と文化（コリア語）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            215 => [
                'id' => 216,
                'name' => '言語文化研究（ヨーロッパ）1',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            216 => [
                'id' => 217,
                'name' => '言語文化研究（ヨーロッパ）2',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            217 => [
                'id' => 218,
                'name' => '言語文化研究（アジア）1',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            218 => [
                'id' => 219,
                'name' => '言語文化研究（アジア）2',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            219 => [
                'id' => 220,
                'name' => '言語文化研究（アメリカ）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            220 => [
                'id' => 221,
                'name' => '海外語学短期研修1（外国語） ',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            221 => [
                'id' => 222,
                'name' => '海外語学短期研修2（外国語）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            222 => [
                'id' => 223,
                'name' => '海外語学中期研修1（外国語）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            223 => [
                'id' => 224,
                'name' => '海外語学中期研修2（外国語）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            224 => [
                'id' => 225,
                'name' => '海外語学中期研修3（外国語）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            225 => [
                'id' => 226,
                'name' => '海外語学中期研修4（外国語）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            226 => [
                'id' => 227,
                'name' => '海外語学中期研修5（外国語）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            227 => [
                'id' => 228,
                'name' => '海外語学中期研修6（外国語）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            228 => [
                'id' => 229,
                'name' => '海外語学中期研修7（外国語）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            229 => [
                'id' => 230,
                'name' => '海外語学中期研修8（外国語）',
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
        ]);
    }
}
